version: '3.8'

services:
  signer-node:
    build: .
    container_name: kipu_signer_node
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DEBUG_SIGNER=true
    restart: always
    networks:          # ← mismo nivel que ports, volumes, etc.
      - red_infraestructura

networks:
  red_infraestructura:
    external: true
